name: Bash Script Workflow
on:
  push:
    branches:
      - main
      - development

jobs:
  run_bash_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run Bash script
        run: bash start.sh

